buildscript {

  repositories {
    mavenCentral()
    google()

  }
  dependencies {
    classpath("com.google.firebase:firebase-crashlytics-gradle:3.0.6")
    classpath("com.android.tools.build:gradle:${libs.versions.androidPluginVersion.get()}")
    classpath("org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:3.3")
    classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${libs.versions.kotlinVersion.get()}")
    classpath("org.jetbrains.kotlin:kotlin-allopen:${libs.versions.kotlinVersion.get()}")
    classpath("org.jacoco:org.jacoco.core:0.8.14")
  }
}

plugins {
  alias(libs.plugins.ksp) apply false
  id "com.diffplug.spotless" version "8.0.0"
}

repositories {
  mavenCentral()
  google()
  maven {
    url("https://oss.sonatype.org/content/repositories/snapshots")
  }
  maven {
    url("https://jcenter.bintray.com/")
  }
}

subprojects {
  repositories {
    mavenCentral()
    google()
    maven {
      url("https://oss.sonatype.org/content/repositories/snapshots")
    }
    //jcenter() // Currently required by url-manager
    maven {
      url("https://jcenter.bintray.com/")
    }

    maven {
      url("https://kingargyle.github.io/repo")
    }
    maven {
      url("https://jitpack.io")
    }
  }

  apply plugin: "com.diffplug.spotless"

  spotless {
      format 'xml', {
          target '**/layout*/*.xml'
          leadingTabsToSpaces(2)
          eclipseWtp('xml').configFile rootProject.file('spotless.xml.prefs')
      }
      groovyGradle {
          target '*.gradle' // default target of groovyGradle
          greclipse()
      }
      kotlinGradle {
          target('*.gradle.kts') // default target for kotlinGradle
          ktlint() // or ktfmt() or prettier()
      }
      kotlin {
          ktlint("1.8.0")
          target('src/**/*.kt')
      }
      java {
          target('src/**/*.java')
          googleJavaFormat()
      }
  }

 tasks.withType(Test).configureEach {

   testLogging {
     exceptionFormat = "full"
   }
  }

  allprojects {
    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
      kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
      }
    }
  }

}
