apply plugin: "jacoco"

tasks.withType(Test).configureEach {
    jacoco.includeNoLocationClasses = true
    jacoco.excludes = ['jdk.internal.*']
}

tasks.register('jacocoTestReport', JacocoReport) {
    dependsOn 'testDebugUnitTest'

    reports {
        xml.required = true
        html.required = true
    }

    def fileFilter = [
        '**/R.class',
        '**/R$*.class',
        '**/BuildConfig.*',
        '**/Manifest*.*',
        '**/*Test*.*',
        'android/**/*.*',
        '**/*MemberInjector.*',
        '**/*$$Factory*.*',
        '**/*..State*.*',
        '**/*_ViewBinding*.*',
        'com/bumptech/**/*.*',
        '**/injection/**/*.*',
        '**/*__Factory*.*',
        '**/*PresenterBinder*.*',
        '**/*ViewState*.*',
        '**/*$ViewBinder*.*',
        '**/*$State*.*',
        '**/*_MembersInjector*.*',
        '**/*$MembersInjector*.*',
        '**/*_Factory*.*',
        '**/*$Factory*.*',
        '**/*Binding.class',
        '**/Emitters*.*',
        '**/SafeCollector.common.*',
        '**/*PresentersBinder*.*',
        '**/Comparisons*.*'
    ]
    def mainSrc = "${project.projectDir}/src/main/java"
    def kotlinSrc = "${project.projectDir}/src/main/kotlin"

    classDirectories.setFrom(fileTree(
            dir: "$buildDir/intermediates/javac/debug/compileDebugJavaWithJavac/classes",
            includes: ['us/nineworlds/serenity/**'],
            excludes: fileFilter) + fileTree(
            dir: "$buildDir/tmp/kotlin-classes/debug",
            includes: ['us/nineworlds/serenity/**'],
            excludes: fileFilter))

    // sources
    sourceDirectories.setFrom(files([
            mainSrc,
            kotlinSrc
    ]))

    executionData.setFrom(files("${buildDir}/jacoco/testDebugUnitTest.exec"))
}
